#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

- name: "enable epel yum repo (Red Hat)"
  block:
    - name: "check if epel is installed"
      shell: "rpm -q --quiet epel-release"
      register: epel_installed
      failed_when: epel_installed.rc == 2
    - name: "install epel on Red Hat"
      shell: "sudo yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
      when: epel_installed.rc == 1
  when: ansible_distribution == "RedHat"
- name: "enable epel yum repo (CentOS)"
  block:
    - name: "enable epel yum repo (CentOS)"
      yum: name=epel-release state=present
      register: epelresult
      retries: 10
      delay: 15
      until: epelresult is not failed
  when: ansible_distribution == "CentOS"
- name: "install packages"
  yum:
    name:
      - vim
      - git
      - wget
      - gcc-c++
      - collectd
      - screen
      - patch
      - "{{ java_package }}"
      - collectd-zookeeper
      - policycoreutils-python
    state: present
  register: yumresult
  retries: 10
  delay: 15
  until: yumresult is not failed
- name: "enable SELinux (Red Hat)"
  block:
    - name: "check if container-selinux is installed"
      shell: "rpm -q --quiet container-selinux"
      register: container_selinux_installed
      failed_when: container_selinux_installed.rc == 2
    - name: "install container-selinux"
      # This makes docker work on RHEL 7
      shell: "sudo yum -y install http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.107-1.el7_6.noarch.rpm"
      when: container_selinux_installed.rc == 1
  when: ansible_distribution == "RedHat"
- name: "configure node shutdown"
  shell: shutdown +{{ shutdown_delay_minutes }} &> {{ user_home }}/.shutdown creates={{ user_home }}/.shutdown
  when: shutdown_delay_minutes > 0
- name: "create install directory on all hosts"
  file: path={{ install_dir }} state=directory owner={{ cluster_user }} group={{ cluster_group }}
- name: "install maven"
  unarchive: src={{ tarballs_dir }}/{{ maven_tarball }} dest={{ install_dir }} creates={{ maven_home }}
- name: "chown maven home"
  file: path={{ maven_home }} recurse=yes owner={{ cluster_user }} group={{ cluster_group}}
- name: "install hub"
  unarchive: src={{ tarballs_dir }}/{{ hub_tarball }} dest={{ install_dir }} creates={{ hub_home }}
  when: install_hub
- name: "chown hub home"
  file: path={{ hub_home }} recurse=yes owner={{ cluster_user }} group={{ cluster_group}}
  when: install_hub
- name: "configure collectd"
  template: src=etc/collectd.conf.j2 dest=/etc/collectd.conf
  when: ('metrics' in groups) or (cluster_type == 'azure')
  notify:
    - restart collectd
- name: "ensure collectd is running (and enable it at boot)"
  service: name=collectd state=started enabled=yes
  when: ('metrics' in groups) or (cluster_type == 'azure')
